In [ ]:
#1:13:14

In [2]:
#建立list
a = [1, 3, 5, 7, 9]      #如果直接a*2 會變成[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8, 10]
a + b                   # a+b 則會變成[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

result = []             
for i in range(5): 
    result.append(a[i] + b[i])  # 需要用到方法append才能真爭把[a]+[b]list


result   

[3, 7, 11, 15, 19]

In [7]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9]) #array是方法
a_array * 2

b_array = np.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [38]:
#使用python建立5個亂數元素的list
import random

#list comprehenstion
[random.randint(50,100) for _ in range(5)]  #50~100之間，包含100 執行5次

[77, 86, 83, 74, 59]

In [33]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)  #不含high數字本身

array([75, 92, 83, 73, 87])

In [51]:
np.random.randint(50,high=100,size=(50, 5))  #隨機生成50~100之間，不含100；共有50行，每行有5個元素
#1:44:13

array([[59, 79, 64, 87, 87],
       [54, 84, 70, 94, 68],
       [86, 85, 70, 90, 61],
       [68, 82, 87, 79, 53],
       [52, 63, 74, 91, 91],
       [67, 77, 51, 78, 93],
       [50, 66, 87, 63, 84],
       [58, 55, 62, 82, 68],
       [96, 68, 76, 97, 72],
       [96, 58, 58, 81, 78],
       [82, 92, 50, 79, 88],
       [89, 81, 79, 69, 78],
       [81, 55, 76, 62, 81],
       [57, 61, 64, 64, 60],
       [58, 85, 74, 66, 94],
       [61, 90, 53, 75, 82],
       [55, 91, 79, 79, 91],
       [54, 79, 92, 90, 53],
       [81, 69, 64, 78, 84],
       [76, 75, 62, 71, 62],
       [92, 62, 93, 98, 59],
       [59, 83, 76, 96, 57],
       [96, 61, 51, 63, 59],
       [59, 95, 62, 53, 50],
       [57, 85, 84, 74, 69],
       [79, 67, 88, 63, 98],
       [51, 93, 70, 93, 62],
       [77, 70, 88, 61, 51],
       [50, 79, 91, 64, 82],
       [82, 69, 78, 75, 90],
       [63, 75, 81, 60, 82],
       [67, 77, 96, 78, 87],
       [97, 51, 63, 80, 83],
       [96, 85, 53, 97, 81],
       [78, 87