In [8]:
#1:13:14

In [9]:
#建立list
a = [1, 3, 5, 7, 9]      #如果直接a*2 會變成[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8, 10]
a + b                   # a+b 則會變成[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

result = []             
for i in range(5): 
    result.append(a[i] + b[i])  # 需要用到方法append才能真爭把[a]+[b]list


result   

[3, 7, 11, 15, 19]

In [10]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9]) #array是方法
a_array * 2

b_array = np.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [11]:
#使用python建立5個亂數元素的list
import random

#list comprehenstion
[random.randint(50,100) for _ in range(5)]  #50~100之間，包含100 執行5次

[59, 95, 79, 70, 59]

In [12]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)  #不含high數字本身

array([87, 57, 89, 73, 58])

In [13]:
np.random.randint(50,high=100,size=(50, 5))  #隨機生成50~100之間，不含100；共有50行，每行有5個元素
#1:44:13

array([[86, 97, 54, 86, 63],
       [73, 81, 66, 76, 86],
       [77, 60, 90, 50, 77],
       [88, 82, 93, 74, 75],
       [52, 68, 82, 65, 78],
       [51, 94, 99, 54, 99],
       [77, 63, 95, 74, 88],
       [97, 75, 72, 97, 76],
       [50, 54, 50, 53, 96],
       [93, 65, 84, 64, 81],
       [87, 85, 66, 97, 82],
       [98, 73, 80, 86, 56],
       [52, 81, 81, 65, 82],
       [79, 51, 94, 74, 63],
       [58, 81, 99, 88, 83],
       [87, 66, 77, 72, 54],
       [75, 84, 92, 66, 51],
       [66, 53, 77, 75, 94],
       [56, 82, 84, 73, 52],
       [85, 92, 80, 64, 76],
       [95, 99, 75, 57, 92],
       [75, 87, 65, 60, 68],
       [89, 91, 94, 52, 72],
       [78, 63, 63, 70, 79],
       [94, 85, 67, 88, 76],
       [70, 75, 80, 96, 73],
       [78, 96, 62, 90, 55],
       [67, 80, 87, 93, 86],
       [55, 79, 84, 86, 50],
       [71, 79, 85, 83, 78],
       [91, 67, 97, 52, 52],
       [70, 67, 50, 95, 87],
       [85, 93, 78, 67, 99],
       [65, 54, 58, 55, 96],
       [56, 55